name: Create Release

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 14.21.3
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Generate docs
        run: node sdkdo docs
      - name: Package JSON Info
        run: echo "SPLUNK_SDK_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
      - run:
      - name: Upload Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: js_sdk_docs
          path: docs-${{ env.SPLUNK_SDK_VERSION }}/
