name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.21.3, 24.5.0]
        splunk-version: ["9.4", "latest"]
    services:
      splunk:
        image: splunk/splunk:${{ matrix.splunk-version }}
        env:
          SPLUNK_START_ARGS: --accept-license
          SPLUNK_HEC_TOKEN: 11111111-1111-1111-1111-1111111111113
          SPLUNK_PASSWORD: changed!
          SPLUNK_APPS_URL: https://github.com/splunk/sdk-app-collection/releases/latest/download/sdkappcollection.tgz
        ports:
          - 8000:8000
          - 8088:8088
          - 8089:8089
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up environment variables
        run: cp ./.env.template ./.env
      - name: Install dependencies
        run: npm install
      - name: Run test suite
        run: node sdkdo tests
        env:
          SPLUNK_HOME: /opt/splunk
  fossa-scan:
    uses: splunk/oss-scanning-public/.github/workflows/oss-scan.yml@main
    secrets: inherit
